version: '3.8'

services:
    artists:
        build:
            context: ./artists/
        ports:
        - 8000:5000
        volumes:
        - ./artists/:/app

    songs:
        build:
            context: ./songs/
        ports:
        - 8001:5001
        volumes:
        - ./songs/:/app

    mysqldb:
        image: mysql
        ports:
        - 3306:3306
        environment:
        - MYSQL_ROOT_PASSWORD=p@ssw0rd1
        volumes:
        - mysql:/var/lib/mysql
        - mysql_config:/etc/mysql

volumes:
    mysql:
    mysql_config:

